name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
        id-token: write # Required for authentication using OIDC
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'
    - run: flutter pub get
    - name: Install pubspec version bump
      run: dart pub global activate pubspec_version
    - name: Bump version
      run: dart pub global run pubspec_version:bump patch
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump version"
    - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1